### ISSUE TITLE
Error with specAcceptHeaders in generated methods

### ISSUE THREAD

**Issue by ehennestad** [mathworks-ref-arch/matlab-openapi-generator#2]
First of all, great tool! Once the installation of dependencies was done, building the api client was very easy.

I am getting an error due to the following code which is present in all the methods generated for an API Client:

```
            % Verify that operation supports returning JSON
            specAcceptHeaders = [...
                "*/*", ...
            ];
            if ismember("application/json",specAcceptHeaders)
                request.Header(end+1) = matlab.net.http.field.AcceptField('application/json');
            else
                error("OpenAPIClient:api:executeQueryById:UnsupportedMediaType","Generated OpenAPI Classes only support 'application/json' MediaType.\n" + ...
                    "Operation '%s' does not support this. It may be possible to call this operation by first editing the generated code.","executeQueryById")
            end
```

This is the openapi spec I have used: https://core.kg.ebrains.eu/v3/api-docs/v3

I assume there is some information either missing from the spec, or not being properly translated? 

Any help would be appreciated!

**Comment by brownemi** [comment]
Hi @ehennestad

Glad you like it! I hope it is useful to you.

Unfortunately the generator can only create code based on what the spec describes.
In this case the `*/*` means that the return type is not defined. If it is JSON then the generator can map that into a MATLAB object ideally parsed based on a schema also defined in the spec. So the error you see acts as somewhat of an opportunity to "insert code here" based on what you might know the API actually does e.g. handle non JSON response appropriately. This sort of custom code might typically strcmp against the operation i.e. "executeQueryById" and could also factor in input parameters.

However in this case I think it can be simpler. The spec describes that in the case of success (http 200) a `#/components/schemas/PaginatedStreamResultJsonLdDoc` is returned and this is defined in the spec too so it can be turned in to a MATLAB object.

In the associated example it looks like:

```json
{
  "data": {
    "parallel": true
  },
  "message": "string",
  "error": {
    "code": 0,
    "message": "string",
    "instanceId": "3fa85f64-5717-4562-b3fc-2c963f66afa6"
  },
  "startTime": 0,
  "durationInMs": 0,
  "total": 0,
  "size": 0,
  "from": 0
}
```

Changing spec line 2812 below from `*/*` to `application/json` should allow the generator to handle this case automatically.

```json
"responses": {
                "200": {
                    "description": "OK",
                    "content": {
                        "*/*": {
                            "schema": {
                                "$ref": "#/components/schemas/PaginatedStreamResultJsonLdDoc"
                            }
                        }
                    }
                }
            }
```

What this spec does not define and perhaps this is the motivation for the `*/*` is what to do in the non 200 error cases.
Sometimes a generic JSON error message structure is defined or different http codes may have different responses. So you may still need some custom code for that depending how you want to deal with error handling.

I note that this arises throughout the spec. so perhaps it is primarily targeted at another generator that takes the liberty of assuming `application/json` or just returns raw data, but that is speculation on my part.

Hope this helps.

**Comment by ehennestad** [comment]
Thanks for your very detailed answer!

> So the error you see acts as somewhat of an opportunity to "insert code here" based on what you might know the API actually does e.g. handle non JSON response appropriately. 

Do you imply that I should edit the generated methods to handle responses in a customized manner?

> I note that this arises throughout the spec. 

Yes, what worked for me was to cmd-F and replace all  `*/*` with `application/json` (There were some ~40 instances). 

> so perhaps it is primarily targeted at another generator that takes the liberty of assuming application/json or just returns raw data, but that is speculation on my part.

Yes, I know the developers behind it have both `java` and `python` clients for the api, so that might be the case.

**Comment by brownemi** [comment]
Yes, while the code is generated, it is relatively readable and and so adding some custom data processing or error handling should not be too difficult if you're familiar with the API and the returned data is in a reasonable format, but of course this will be very API dependant.

However, I think in your case the change to the spec is the simpler solution and have the generator do the work. The downside is that error cases are not covered but the spec does not hint at what to do with them anyway so in the absence of other documentation you'd have to induce or otherwise capture failures and hand code some error handling accordingly.
