### ISSUE TITLE
Startup.m file conflicts with user's own startup file

### ISSUE THREAD

**Issue by ehennestad** [mathworks-ref-arch/matlab-openapi-generator#7]
I rely on a startup file to set my default search path when MATLAB starts up, and I use some other custom scripts to change the search path for changing between different projects I am working on.

If the openapi-generator is on my search path, it's startup.m file can take precedence over my own startup file. Do you have any suggestions to deal with this? Should the startup file of openapi be in a package, or are there better ways to deal with this?

**Comment by brownemi** [comment]
We provide a startup.m file to add the paths on the assumption that this is a tool that is likely to be used infrequently and so having a script to run on an as needed basis that could be customised and run automatically if MATLAB is set to restart in the previous working directory would be convenient balance. We don't expect the tool to be on the path all the time. But our habits and configurations differ of course...

The generator startup.m file is not required for the generated code and should not be added to such code. You may wish to provide a path handling script as a customisation to generated code depending on how it is to be used.

I see two approaches you could take:

1) Simply change the name of the script, as described in the link below, if the file is not called startup it will not run automatically and the you can call it by other means when an only when you want.

2) While derived from more complex packages in this case the script is not doing too much and reports the paths it adds. You could note those paths and manually add them to your path along with renaming the startup file. The downside being you'd have to manually remove them later if needed. Also updates to the package in the future might change the paths we add.

As you are probably aware the following links describe how startup.m can be used and path order controlled.
https://www.mathworks.com/help/matlab/ref/startup.html
https://www.mathworks.com/help/matlab/matlab_env/add-remove-or-reorder-folders-on-the-search-path.html
https://www.mathworks.com/help/matlab/ref/addpath.html
