### ISSUE TITLE
openapitools.json is saved in the current working directory

### ISSUE THREAD

**Issue by ehennestad** [mathworks-ref-arch/matlab-openapi-generator#8]
This is not a big deal, but would be convenient if it could be saved in a specified location.

**Comment by brownemi** [comment]
If you use the `configurationFile` value as a named argument then you should be able to do this e.g.:
builder = openapi.build.Client(configurationFile='/home/username/mydirectory/myfile.json', etc. etc.)   assuming a UNIX style path.
Let us know if this doesn't work for you.

You can also disable generation of this file using useConfigurationFile=false, though this option may be removed in a future release.

**Comment by ehennestad** [comment]
I tried to set the configurationFile property using dot notation and it did not work. A file was still generated in the current working directory and later there was an error that configuration file was not found. I can repost the ertor later
